version: "3.4"

services:
  weather_forecast:
    build: ./weatherForecast
    ports:
      - "10000:80"
    restart: always
    depends_on:
      - "rabbitmq"      

  manage_weather_forecast:
    build: ./manageForecast
    ports:
      - "10005:80"
    restart: always
    depends_on:
      - "weather_forecast"
      - "rabbitmq"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"